### ISSUE TITLE
[MPT-17] index: Testimonial Carousel

### ISSUE THREAD

**Issue by jcc-kh** [AdvisorySG/mentorship-page#575]
Testimonials (featuring a pair of mentors and mentees) could be featured in the form of carousel (i.e swipes and changes to the next one after 5 seconds when users stop on the page), would be placed under home page (which is mentorship program

<sub>[MPT-17](https://linear.app/advisorysg/issue/MPT-17/testimonial-carousel)</sub>

**Comment by wei2912** [comment]
I have integrated @luodan01's code from https://github.com/AdvisorySG/mentorship-page/pull/601, which uses Material UI components. @yashchellani has also written some code at https://github.com/AdvisorySG/mentorship-page/pull/596 which is closer to the intended design, but because this code is taken from a tutorial, it would be preferable to adapt @luodan01's past code to follow @yashchellani's proposal.

Please follow the latest code at https://github.com/AdvisorySG/mentorship-page/tree/multi-page.

**Comment by wei2912** [comment]
@angelangweihan will be creating a prototype loosely based off the https://glidejs.com/ library (which we are also using in GPT at https://github.com/AdvisorySG/dawn-advisory-theme/blob/main/assets/js/main.js#L7).
After this prototype is done, @jeffzy15 is to implement the carousel as requested.

Requirements for @jeffzy15:
1. Develop testimonial carousel such that the component is compatible with Node v18 (see https://github.com/AdvisorySG/mentorship-page/issues/650).
2. Specify testimonials and photos in format of JSON data (see https://github.com/AdvisorySG/mentorship-page/pull/596/files#diff-aa98fd0757d0e1741503c50cfafb7726939d19819638bbe8e030a27adfec34a3 for e.g., feel free to change the schema if you prefer)
3. (Responsive design to be left to a separate task.)

**Comment by wei2912** [comment]
See prototype on Telegram.
